Shining-Jicheon-Stars/yjg-laravel-backend

database/migrations/2024_01_18_071727_create_notices.php, database/migrations/2024_01_18_072030_create_notice_images.php, database/migrations/2024_01_18_072139_create_salon_reservations.php, database/migrations/2024_01_18_072410_create_salon_menu.php, database/migrations/2024_01_18_072535_create_meeting_room_reservations.php, database/migrations/2024_01_18_072648_create_meeting_rooms.php, database/migrations/2024_01_18_072736_create_sleepover_lists.php, database/migrations/2024_01_18_072851_create_bus_times.php
=> Feat : Create migration file

app/Http/Kernel.php, app/Models/AfterService.php, app/Models/AfterServiceComment.php, app/Models/AfterServiceImage.php, app/Models/RestaurantMenu.php, app/Models/RestaurantSemester.php, app/Models/RestaurantWeekend.php, app/Models/User.php, composer.json, composer.lock, database/migrations/2024_01_18_072410_create_salon_reservations_table.php, database/migrations/2024_01_18_080008_create_restaurant_menus_table.php, database/migrations/2024_01_18_080551_create_after_services_table.php, database/migrations/2024_01_18_081604_create_after_service_comments_table.php
> #7 , #3 , #6 
> 1. 마이그레이션 파일 수정
> 2. 로그인 기능 구현을 위한 socialite, sanctum 설치
> 3. A/S, 식당, 유저 관련 모델 작성 
> 모델 연관관계 정의 이상없는지 확인해주세요
=> Feat: モデル作成

app/Exceptions/DestroyException.php, app/Http/Controllers/Controller.php, app/Http/Controllers/UserController.php, composer.json, composer.lock, config/app.php, config/l5-swagger.php, resources/views/vendor/l5-swagger/index.blade.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #6 
> 1. 회원가입, 탈퇴 기능 구현
> 2. Swagger 사용을 위한 `L5-Swagger` 패키지 추가
> 
=> Feat: 会員登録、脱退機能追加

app/Http/Controllers/Controller.php, app/Http/Controllers/LoginController.php, app/Http/Controllers/UserController.php, database/migrations/2014_10_12_000000_create_users_table.php, database/migrations/2024_01_18_080551_create_after_services_table.php, database/migrations/2024_01_24_104549_create_after_service_images_after_service_table.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #11
> 웹 및 앱 로그인 기능 구현
> 마이그레이션 파일 수정 (pivot 테이블 추가, 컬럼 추가)
> 
=> Feat: ログイン機能実装

app/Http/Controllers/AdminController.php, app/Models/Admin.php, database/migrations/2024_01_25_101725_create_admins_table.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #14 #15 #17
> 관리자 권한 부여 기능
> user 테이블과 admin 테이블 분리
> 관리자 회원가입 승인 기능
> 관리자 개인정보 수정 기능
> 
=> Feat: 管理者の権限付与機能実装

app/Http/Controllers/AdminController.php, app/Http/Controllers/Controller.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #18 #19 
> 이메일 중복 확인 기능 구현
> 현재 인증된 유저와 입력한 비밀번호 일치 여부 기능 구현
> 
=> Feat: パスワード、メール確認実装

app/Http/Controllers/AdminController.php
> ex) #6
> 계정 생성 시 HTTP 상태 코드 변경
> 
=> Refactor: HTTPステータスコード変更

app/Http/Kernel.php, config/auth.php, config/cors.php, database/migrations/2014_10_12_000000_create_users_table.php, database/migrations/2024_01_25_101725_create_admins_table.php
> ex) #28 #30 #31
> 추후 다중인증 구현을 위해 프로바이더 명 변경
> sanctum 인증 오류로 인해 미들웨어 그룹에 세션 관련 미들웨어 추가
> 외국인 이용자를 가정하여 users & admins의 휴대폰 번호, 이름 컬럼 사이즈 확장
> CORS 에러 발생으로 인하여 config 파일 수정
> 
=> !HOTFIX: CORSエラー解決

app/Http/Controllers/AdminController.php, app/Models/Admin.php, routes/api.php
=> Fix: メール確認機能エラー解決

Dockerfile
=> !HOTFIX: Update Dockerfile

app/Http/Controllers/AdminController.php, database/factories/AdminFactory.php, database/migrations/2024_01_25_101725_create_admins_table.php, database/seeders/AdminTestSeeder.php, database/seeders/DatabaseSeeder.php, routes/api.php, storage/api-docs/api-docs.json, tests/Feature/AdminTest.php, tests/TestCase.php
> ex) #54 #56 #57
> 총 관리자 권한 부여를 위한 master 컬럼 추가
> 테스트 코드 작성을 위한 Seeder와 Factory 추가
> 라우트에 prefix를 통하여 코드 정리
> 이름과 전화번호를 통한 이메일 찾기 로직 구현
> AdminController 관련 테스트 코드 작성 (아직 구현 못한 비밀번호 찾기 로직 제외) 및 이를 통한 소소한 에러 해결
> 
=> Feat: メール検索実装

app/Http/Controllers/AuthController.php, app/Http/Controllers/UserController.php
> ex) #61 
> 학교 이메일 만을 이용하여 로그인하도록 구현
> 
=> Feat: G suiteメールだけを許可する機能実装

app/Http/Controllers/AdminController.php, app/Http/Controllers/UserController.php, database/migrations/2014_10_12_000000_create_users_table.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #64 #63 #67 #65 #66 
> 유학생 회원가입 승인을 위한 스키마 변경
> 유학생 회원가입, 로그인 기능 구현(로그아웃은 기존 기능 공유)
> 유학생 회원 탈퇴 기능 구현
> 유학생 회원 승인 기능
> 유학생 회원 승인 or 미승인 목록 기능 
> 
=> Feat: 外国人会員登録、ログイン機能実装

app/Http/Controllers/SalonCategoryController.php, app/Http/Controllers/SalonReservationController.php, app/Http/Controllers/SalonServiceController.php, app/Models/Admin.php, app/Models/SalonCategory.php, app/Models/SalonPrice.php, app/Models/SalonReservation.php, app/Models/SalonService.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #42 #43 #44 #69 #70 #71 #40 #41 
> 미용실 카테고리 및 서비스 생성, 수정, 삭제 구현
> admins 테이블 대량할당 시 취약성 보호를 위해 fillable 수정
> 미용실 API 문서 생성 및 작성
> 미용실 예약 목록 반환 및 예약 상태 수정 기능 구현
> 
=> Feat: 美容室関連機能実装

.github/CODEOWNERS
> ex) X
> .github 리포지토리에 CODEOWNERS 등록 후 삭제합니당
> 
=> Remove: CODEOWNERSを削除

.github/CODEOWNERS, auto_assign_test.md
> ex) #80 #81
> PR 업로드 시 Assignees 자동 등록 테스트
> CODEOWNERS 생성 (PR 리뷰어 자동 등록)
> 
=> Test: Assignee自動化テスト

.github/CODEOWNERS, auto_assign_test.md
> ex) #80 #81 
> CODEOWNERS 수정
> auto_assign 테스트
> 
=> Test: Assignees自動化テスト

auto_assign_test.md
=> Test: Reviewerテスト

app/Http/Controllers/Admin/AdminSalonReservationController.php
> ex) #40 
> 유저명, 서비스명 같이 반환하도록 수정
> 
=> Fix: 予約機能改善

app/Http/Controllers/Admin/AdminController.php, app/Http/Controllers/Admin/AdminSalonReservationController.php, database/migrations/2024_01_18_080008_create_restaurant_menus_table.php, storage/api-docs/api-docs.json
> ex) #40 
> 미용실 예약 검색 기능 룰 추가 및 개선
> 관리자 검색 기능 파라미터 타입 변경 및 검색 오류 해결
> restaurant_menus 테이블 수정
> 
=> Fix: 管理者検索機能エラー解決

app/Models/SalonReservation.php, database/migrations/2024_01_29_070101_create_salon_reservations_table.php, database/seeders/DatabaseSeeder.php, database/seeders/SalonSeeder.php
> ex) #117 #118 
> 미용실 예약 테이블 스키마 변경
> 미용실 가격표를 위한 시더 생성 (현재는 임시데이터, 추후에 참조하여 삽입예정)
> 
=> Migration: salon_reservationsスキーマ変更

composer.json, composer.lock
> ex) X
> Laravel Socialite 버전 업데이트
> 
=> Chore: Socialiteをアップデート

.github/CODEOWNERS
> ex) X
> 팀 이외에도 개인에게 리뷰를 할당할 수 있도록 변경
> 
=> Chore: CODEOWNERSを修正

app/Http/Controllers/Admin/AdminController.php
> ex) #124
> 관리자 메일 체크 기능 에러 수정
> 
=> Fix: メールチェック機能エラー解決

app/Http/Controllers/Admin/AdminController.php
> ex) #126 
> unapproved 요청 시에도 배열로 반환되도록 수정
> 
=> Fix: 管理者リスト機能修正

app/Http/Controllers/QRController.php, routes/api.php
=> Fix:QRControllerを修正

app/Http/Controllers/Admin/AdminSalonReservationController.php, app/Http/Controllers/Admin/SalonBreakTimeController.php, app/Http/Controllers/Admin/SalonBusinessHourController.php, app/Http/Controllers/User/UserController.php, app/Http/Controllers/User/UserSalonReservationController.php, app/Models/SalonBreakTime.php, app/Models/SalonBusinessHour.php, database/migrations/2024_01_18_072648_create_meeting_room_reservations_table.php, database/migrations/2024_01_18_080008_create_restaurant_menus_table.php, database/migrations/2024_01_18_080551_create_after_services_table.php, database/migrations/2024_01_18_081448_create_after_service_images_table.php, database/migrations/2024_01_18_081604_create_after_service_comments_table.php, database/migrations/2024_01_24_104549_create_after_service_images_after_service_table.php, database/migrations/2024_01_29_070101_create_salon_reservations_table.php, database/migrations/2024_02_17_164313_create_salon_break_times_table.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #131 #132 #133 #136 #138 #140 #141 
> 미용실 영업시간 관련 기능 구현 (불러오는 기능 제외)
> 미용실 예약불가 시간 관련 기능 구현 (불러오는 기능 제외)
> 영업시간 및 예약불가 시간 관련 테이블 스키마 수정
> 마이그레이션 파일 오류 수정
> API 문서 오류 수정
> 관리자 미용실 예약 관련 기능 수정 (시간 및 날짜를 받아 검색하도록 수정)
> 
=> Feat: 美容室の営業時間関連機能実装

.gitignore, app/Http/Controllers/Admin/AdminController.php, app/Http/Controllers/Admin/AdminSalonReservationController.php, app/Http/Controllers/Admin/SalonServiceController.php, app/Http/Controllers/User/UserController.php, app/Http/Controllers/User/UserSalonReservationController.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #148 #150
> 학생 회원정보 기능 수정
> 관리자 권한 수정 기능 개선
> 학생 이메일 중복 검사 기능 구현
> 바뀐 미용실 테이블에 맞게 관련 로직 수정
> .gitignore 수정
> 
=> Feat: ユーザーのメール確認機能実装

app/Http/Controllers/Admin/AdminController.php, app/Http/Controllers/Controller.php, app/Http/Controllers/User/UserController.php, routes/api.php, storage/api-docs/api-docs.json
> ex) X
> 유효성 검사 규칙 변경
> API 문서 수정
> 동일명을 가지는 함수명 수정
> 
=> Refactor: validationルールを修正

app/Http/Controllers/Admin/AdminController.php, app/Http/Controllers/User/UserController.php
> ex) #135 
> Swagger로 인해 Actions에서 도커 이미지 빌드 시 발생하던 에러 해결
> 
=> Fix: API文書関連エラー解決

app/Http/Controllers/Admin/AdminSalonReservationController.php, app/Http/Controllers/Admin/SalonBreakTimeController.php, app/Http/Controllers/Admin/SalonBusinessHourController.php, app/Http/Controllers/Controller.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #134 #139 
> 미용실 영업시간 관련 기능 구현
> 
=> Feat: 美容室営業時間関連機能実装

app/Http/Controllers/Admin/AdminSalonReservationController.php, app/Http/Controllers/Admin/SalonServiceController.php, routes/api.php
> ex) #156 #157 
> 서비스 성별 검색 기능을 수정하였습니다.
> 이전 TimeCast 적용 커밋에 누락된 파일을 추가하였습니다.
> 
=> Feat: TimeCastを適用

app/Http/Controllers/Admin/SalonBusinessHourController.php, app/Http/Controllers/Controller.php, app/Imports/UsersImport.php, database/seeders/DatabaseSeeder.php, database/seeders/SalonBusinessHourSeeder.php, database/seeders/UserSeeder.php
> ex) #162 #163 #164 
> 미용실 영업시간 시더를 구현
> Laravel Excel을 이용한 유저 시더 구현
> 미용실 영업시간을 불러오는 기능 에러 수정
> 
=> Feat: Seederを実装

app/Http/Controllers/Admin/AdminController.php, app/Http/Controllers/Admin/SalonBusinessHourController.php, app/Http/Controllers/User/UserSalonReservationController.php, config/app.php, lang/kr/validation.php
> ex) #149 
> 한국어 유효성 검사 파일 적용을 위해 locale 변경
> DB에 저장되는 시간 값을 올바르게 설정하기 위해 timezone을 서울로 변경
> 한국어 유효성 검사 메세지 작성
> 전반적인 유효성 검사 규칙 수정
> 
=> Feat: 韓国語のvalidationメッセージファイルを生成

database/migrations/2024_01_18_081839_create_restaurant_semesters_table.php, database/migrations/2024_01_18_082155_create_restaurant_weekends_table.php, database/migrations/2024_02_17_164313_create_salon_break_times_table.php, database/migrations/2024_02_21_212448_create_semester_meal_type_table.php, database/migrations/2024_02_21_212458_create_weekend_meal_type_table.php, database/migrations/2024_02_21_212817_create_restaurant_weekend_meal_type_table.php, database/migrations/2024_02_21_212823_create_restaurant_semester_meal_type_table.php
> ex) #168 
> 식당 및 식사 신청 관련 테이블 ERD에 맞게 수정
> 스키마 이상없는지 봐주세요.
=> Migration: レストラン関連テーブルを修正

.github/workflows/issue_assignee.yml, .github/workflows/main.yml
> ex) X
> 이슈 등록시 Assignees 자동화 구현
> CI 과정 간소화
> 
=> Chore: Issueにassignees自動化実装

routes/api.php
=> Fix: ログインAPIメソッドエラーを解決

database/factories/MeetingRoomReservationFactory.php, database/seeders/DatabaseSeeder.php, database/seeders/MeetingRoomReservationSeeder.php, database/seeders/MeetingRoomSeeder.php, database/seeders/SalonBusinessHourSeeder.php, database/seeders/SalonSeeder.php, database/seeders/UserSeeder.php
> ex) #182 
> A/S 관련 시더 구현
> 기타 시더 및 팩토리 수정
> 
=> Refactor: 行政関連seeder修正

app/Http/Controllers/Admin/SalonServiceController.php, app/Http/Controllers/User/UserController.php, storage/api-docs/api-docs.json
=> Docs: API文書を修正

app/Http/Controllers/Admin/NoticeController.php, app/Models/Notice.php, app/Models/NoticeImage.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #186 #187 #188 
> 공지사항 생성, 수정, 삭제 기능 구현
> 모델을 수정
> 
=> Feat: notice関連機能を実装

app/Models/Notice.php, composer.json, composer.lock, config/scout.php
> ex) #189 
> 공지사항 검색기능 구현을 위한 laravel/scout와 typesense sdk를 설치
> Searchable trait 추가
> 
=> Chore: scoutとtypesenseのsdkを追加

database/factories/NoticeFactory.php, database/seeders/DatabaseSeeder.php, database/seeders/NoticeSeeder.php
> ex) #194 
> 공지사항 테스트를 위한 시더와 팩토리 구현
> 
=> Feat: noticeのfactoryとseederを実装

app/Http/Controllers/Admin/SalonBreakTimeController.php, app/Http/Controllers/Admin/SalonServiceController.php, routes/api.php
> ex) #196 
> 필터링하는 값이 없을 경우 모든 서비스를 반환하도록 개선
> API 문서 수정
> 
=> Refactor: 美容室サービス関連機能を改善

app/Http/Controllers/User/UserController.php, app/Http/Controllers/User/UserSalonReservationController.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #193 
> 미들웨어 적용
> 모든 API ID를 미포함하도록 수정
> API 문서 수정
> 
=> Refactor: ユーザー関連機能修正

app/Http/Controllers/Admin/SalonServiceController.php
> ex) #196 
> 키값이 일치하지 않아 발생하던 오류 해결
> 
=> Fix: 美容室サービス関連エラーを修正

app/Http/Controllers/busTimeController.php, app/Models/BusRoute.php, database/migrations/2024_02_27_150408_create_bus_times_table.php
=> bus_route 修正

app/Models/Notice.php
> ex) #189 
> #206 PR에 누락된 커밋 추가 
> 
=> Chore: scoutとtypesenseのsdkを削除

app/Http/Controllers/busTimeController.php, routes/api.php, storage/api-docs/api-docs.json
=> feat: BusTimeController API 制作

app/Http/Controllers/Admin/AdminController.php, app/Http/Controllers/User/UserController.php, app/Models/User.php
> ex) X
> 모델 수정
> 로그인 응답 형태 변경
> 
=> Refactor: ログインレスポンスを変更

app/Http/Controllers/Admin/NoticeController.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #189 
> 공지사항 검색 기능 구현 및 페이지네이션
> 공지사항 아이디로 불러오기 기능 구현
> 공지사항 작성 시 admin_id 요구하는 부분 제거
> 
=> Feat: notice検索機能実装

app/Http/Controllers/Admin/NoticeController.php, docker-compose.yml
=> HOTFIX: docker-composeを修正

app/Http/Controllers/WeekendMealTypeController.php, docker-compose.yml, storage/api-docs/api-docs.json
=> weekendMealType swagger 修正

app/Http/Controllers/Admin/NoticeController.php, app/Models/Admin.php, app/Models/Notice.php
> ex) #186 #189 
> 관리자 연관관계 매핑되도록 모델 수정
> 글 작성 시 이미지 없을 경우 발생하는 에러 해결
> 글 상세 요청 시 관리자 정보 함께 반환하도록 구현
> 
=> Fix: notice作成機能を修正

app/Http/Controllers/Admin/NoticeController.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #187 
> 공지사항 수정 기능 라우트 수정
> 이미지 삭제 시 연관관계 해제
> 아이디 값으로 이미지 삭제하도록 구현
> 
=> Fix: notice生成機能を修正

app/Http/Controllers/Admin/NoticeController.php, storage/api-docs/api-docs.json
> X
> 공지사항을 검색할 때 최신순으로 불러오도록 정렬
> 공지사항 관련 API 문서 수정
> 
=> Refactor: notice検索機能を改善

app/Http/Controllers/User/UserController.php, app/Http/Kernel.php, app/Http/Middleware/ApproveCheck.php, routes/api.php
> ex) #224 
> 사용자의 approved 컬럼을 체크하여 추가정보를 입력한 유저인지 확인
> 
=> Feat: 認証関連のmiddlewareを実装

app/Http/Controllers/BusScheduleController.php, storage/api-docs/api-docs.json
=> fix: bus swagger 修正

app/Http/Controllers/BusScheduleController.php, app/Http/Controllers/RestaurantSemesterController.php, routes/api.php, storage/api-docs/api-docs.json
=> feat: bus_round get API 作成

app/Http/Controllers/Admin/AdminController.php, app/Http/Kernel.php, app/Http/Middleware/AdminApprovedCheck.php, app/Http/Middleware/AdminMasterCheck.php, app/Http/Middleware/UserApproveCheck.php, routes/api.php
> ex) #237 #236  
> 미들웨어를 통해 미승인 관리자 로그인 방지
> 회원탈퇴 로직을 두개로 나누고 마스터 전용 탈퇴 로직에는 미들웨어 적용
> 
=> Fix: admin認証関連エアーを修正

routes/api.php
> ex) X
> 미용실 서비스 요청 API에 대한 권한 수정
> 
=> Fix: 美容室メニュー関連APIの権限を調整

app/Models/User.php
> ex) X
> approved 컬럼이 수정되지 않는 문제 해결을 위해 fillable 재정의
> 
=> Fix: Userモデルのfillableを修正

app/Http/Controllers/Admin/AdminAfterServiceController.php, app/Http/Controllers/Admin/NoticeController.php, app/Http/Controllers/Admin/SalonCategoryController.php, app/Http/Controllers/Admin/SalonServiceController.php, app/Http/Controllers/AfterServiceController.php, app/Http/Controllers/User/UserAfterServiceController.php, app/Models/AfterService.php, database/factories/AfterServiceFactory.php, database/migrations/2024_01_18_080551_create_after_services_table.php, database/seeders/AfterServiceSeeder.php, database/seeders/DatabaseSeeder.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #45 #225 #226 #242
> AS 생성 #225 
> AS 수정 #242
> AS 삭제 #226 
> AS를 상태 및 작성자로 검색할 수 있도록 구현 #45
> AS 팩토리 및 시더 구현
> AS 테이블 날짜 컬럼 추가 및 그에 맞게 모델 수정
> API 문서 수정
> 컨트롤러 관리자 및 유저 별로 파일 구분
> AS 상태 변경 기능 구현 #46 
> 
=> Feat: AS関連機能を実装

app/Http/Controllers/MeetingRoomController.php, app/Http/Controllers/MeetingRoomReservationController.php, app/Models/MeetingRoom.php, app/Models/MeetingRoomReservation.php, database/factories/MeetingRoomReservationFactory.php, database/migrations/2024_01_18_072535_create_meeting_rooms_table.php, database/migrations/2024_01_18_072648_create_meeting_room_reservations_table.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #244 #245 #246 #247 #248 #250 #251 #252
> 회의실 관련 DB 수정(회의실 번호를 주키로 설정)
> 회의실 관련 모델 수정(수정된 스키마에 맞게 연관관계 정의, fillable 수정)
> 회의실 추가 및 삭제 구현
> 특정 회의실의 예약 전체 목록 API 구현
> 현재 유저의 회의실 예약 목록 API 구현
> 예약의 아이디로 회의실 예약 내용을 찾는 API 구현
> 회의실 예약 삭제 API 구현 (해당 유저가 예약을 취소할 때)
> 회의실 예약 거절 API 구현 (관리자의 사정으로 부득이하게 취소할 경우)
> 
=> Feat: 会議室関連機能を実装

app/Http/Controllers/Admin/AdminAfterServiceController.php, app/Http/Controllers/AfterServiceCommentController.php, app/Http/Controllers/User/UserAfterServiceController.php, routes/api.php
> ex) #48 #49 #50 
> AS 댓글 관련 기능 구현
> 작성 수정 삭제 구현
> 
=> Feat: ASのコメント機能実装

app/Http/Controllers/Admin/NoticeController.php, app/Http/Controllers/MeetingRoomReservationController.php, app/Http/Controllers/User/UserController.php, routes/api.php, storage/api-docs/api-docs.json
> ex) X
> 라우트 에러 및 로그인 에러 해결
> 문서 수정
> 
=> Fix: routeエラーおよびログインエラーを解決

app/Http/Controllers/User/UserController.php
=> Fix: googleログインエラーを修正

app/Http/Controllers/User/UserAfterServiceController.php
> ex) X
> 페이지네이션 8개로 수정
> 유저 정보 함께 불러오도록 구현
> 
=> Refactor: ASを読み込む機能の修正

app/Http/Controllers/User/UserController.php, app/Http/Kernel.php, app/Http/Middleware/UserGoogleApprovedCheck.php, routes/api.php
> ex) X
> 기존에 로그인안되던 문제 해결을 위해 일반 로그인과 미들웨어를 따로 구현
> 
=> Feat: googleログイン用middlewareを実装

app/Http/Controllers/Admin/AdminAfterServiceController.php, app/Http/Controllers/MeetingRoomController.php, app/Http/Controllers/User/UserAfterServiceController.php
> ex)X
> AS를 읽어올때 댓글도 함께 가져오도록 구현
> validation 룰 수정, 커스텀 메시지 정의
> 
=> Refactor: AS機能を修正

app/Http/Controllers/BusScheduleController.php, database/migrations/2024_02_29_141433_create_bus_schedules_table.php, routes/api.php
=> fix: bus API 修正

app/Console/Commands/MakeService.php, app/Http/Controllers/Admin/AdminAfterServiceController.php, app/Http/Controllers/MeetingRoomController.php, app/Http/Controllers/MeetingRoomReservationController.php, app/Services/ReservedTimeService.php, lang/kr/validation.php, routes/api.php, storage/api-docs/api-docs.json, stubs/service.stub
> ex) #271 #252 #249 
> 서비스 클래스를 간편하게 생성하기 위한 artisan 명령어 구현
> 특정 회의실 예약목록을 읽어오는 기능 구현
> validation 룰을 수정하고, 메시지 오타 수정
> 예약된 시간을 한시간 단위로 불러오는 서비스가 중복되어 이를 별도의 클래스로 나누고, 기존 사용되던 기능에 적용
> 회의실 예약 기능을 구현 (위에서 생성한 서비스 적용)
> API 문서 수정
> 
=> Feat: 会議室の予約機能を実装

app/Http/Controllers/AbsenceController.php, app/Http/Controllers/MeetingRoomController.php, app/Http/Controllers/MeetingRoomReservationController.php, routes/api.php, storage/api-docs/api-docs.json
> ex) X
> `MeetingRoomController` 에서 특정 회의실의 예약을 반환하는 `show` 메서드를 삭제하고,
이를 `MeetingRoomReservationController` 의 `index` 메서드로 통합시켰습니다. (날짜, 호실을 쿼리로 받음)
> API 문서 수정
> 외박 검색 기능 에러 수정
> 
=> Refactor: 会議室を読み込む機能を修正

app/Http/Controllers/BusScheduleController.php, app/Http/Controllers/WeekendMealTypeController.php, database/migrations/2024_02_21_212448_create_semester_meal_type_table.php, routes/api.php, storage/api-docs/api-docs.json
=> fix: bus get,patch API 修正

app/Http/Controllers/Admin/AdminAfterServiceController.php, app/Http/Controllers/Admin/AdminSalonReservationController.php, app/Http/Controllers/Admin/NoticeController.php, app/Http/Controllers/Admin/SalonBreakTimeController.php, app/Http/Controllers/Admin/SalonBusinessHourController.php, app/Http/Controllers/Admin/SalonCategoryController.php, app/Http/Controllers/Admin/SalonServiceController.php, app/Http/Controllers/AfterServiceCommentController.php, app/Http/Controllers/MeetingRoomController.php, app/Http/Controllers/MeetingRoomReservationController.php, app/Http/Controllers/QRController.php, app/Http/Controllers/RestaurantMenusController.php, app/Http/Controllers/User/UserController.php, app/Http/Controllers/User/UserSalonReservationController.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #281 
> 불필요한 접두사 삭제
> 라우트명을 통일성있게 수정
> RESTful API 설계 규칙에 부합하도록 수정
> 
=> Refactor: routeを整理

app/Http/Controllers/Administrator/AbsenceController.php
> ex) #286 
> 외박/외출 관련 검색 시 학번과 함께 불러오도록 구현
> 
=> Refactor: 外泊関連機能を修正

app/Http/Controllers/Administrator/AbsenceController.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #288 
> 파라미터로 받은 외박, 외출 신청자의 카운트를 반환
> 
=> Feat: 外泊カウント機能を実装

app/Http/Controllers/Administrator/BusScheduleController.php, app/Http/Controllers/Restaurant/RestaurantSemesterController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php, app/Http/Controllers/Restaurant/SemesterMealTypeController.php, app/Http/Controllers/Restaurant/WeekendMealTypeController.php, routes/api.php, storage/api-docs/api-docs.json
=> fix: restaurant fill error

app/Http/Controllers/Administrator/AbsenceController.php, app/Models/SalonReservation.php
> ex) X
> 외박/외출 검색 시 최신순으로 가져오도록 구현
> 미용실 예약 시 에러 해결 (모델의 fillable 수정)
> 
=> Refactor: 外泊検索機能を修正

app/Models/SalonReservation.php
> ex) X
> user_id 대량할당 가능하도록 수정
> 
=> Fix: 美容室の予約エラーを解決

routes/api.php
> ex) X
> API 문서와 동일하도록 사용자의 미용실 예약 정보를 가져오는 라우트 수정
> 
=> Fix: routeを修正

app/Http/Controllers/MeetingRoom/MeetingRoomController.php, app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php, storage/api-docs/api-docs.json
> X
> 회의실 삭제 에러를 수정
> API 문서 오탈자 수정
> 
=> Fix: 会議室関連エラーを修正

app/Http/Controllers/Administrator/BusScheduleController.php, routes/api.php
=> fix: bus API swagger修正

app/Http/Controllers/Restaurant/RestaurantSemesterController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php, app/Http/Controllers/Restaurant/SemesterMealTypeController.php, app/Http/Controllers/Restaurant/WeekendMealTypeController.php, routes/api.php, storage/api-docs/api-docs.json
=> feat: restaurant delete API 作成

app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php, routes/api.php
> ex) X
> 회의실 예약 검색 시, 예약한 유저명까지 반환하도록 수정
> 회의실 거절 기능 라우트 오류 수정
> 
=> Refactor: 会議室の検索機能を修正

app/Http/Controllers/Administrator/AbsenceController.php, app/Http/Controllers/Administrator/NoticeController.php, app/Http/Controllers/AfterService/AfterServiceCommentController.php, app/Http/Controllers/AfterService/AfterServiceController.php, app/Http/Controllers/Auth/AdminController.php, app/Http/Controllers/Auth/UserController.php, app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php, app/Http/Controllers/Salon/SalonReservationController.php, app/Http/Middleware/UserGoogleApprovedCheck.php, app/Models/Admin.php, app/Models/User.php, composer.json, composer.lock, config/auth.php, config/jwt.php, routes/api.php
> ex) #222 #223 
> tymon/jwt-auth 설치
> jwt를 이용하기 위한 모델 및 guard 설정
> 전체 컨트롤러 및 미들웨어를 현재 인증방식에 맞게 수정
> 
=> Feat: 既存のtokenからJWTに改善

app/Http/Controllers/Administrator/BusScheduleController.php, database/migrations/2024_01_18_081839_create_restaurant_semesters_table.php, database/migrations/2024_01_18_082155_create_restaurant_weekends_table.php, database/migrations/2024_03_04_111424_create_bus_routes_table.php
=> fix: bus_routes migration 修正

app/Http/Controllers/Administrator/BusScheduleController.php
=> fix: bus schedule API修正

app/Http/Controllers/AfterService/AfterServiceController.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #308
> 유저의 AS 목록을 불러오는 기능 구현
> 
=> Feat: ユーザーのASを読み込む機能を実装

app/Http/Controllers/AfterService/AfterServiceController.php, config/jwt.php
> ex) #308 
> 유저의 AS를 읽어오는 기능 에러 해결 (커밋 메세지 잘못 함 Fix임)
> 토큰의 유효기간을 10시간으로 수정
> 
=> Refactor: ユーザーのASを読み込む機能を修正

app/Http/Controllers/AfterService/AfterServiceController.php
> X
> 관계 테이블을 전부 같이 불러오도록 수정
> 
=> Refactor: AS関連機能を修正

app/Http/Controllers/Restaurant/RestaurantSemesterController.php
=> fix: restaurant semester API 修正

app/Http/Controllers/Restaurant/RestaurantMenusController.php, app/Models/BusRoute.php, app/Models/RestaurantMenu.php, app/Models/RestaurantMenuMonth.php, database/migrations/2024_03_07_203208_create_restaurant_menu_months_table.php, database/migrations/2024_03_11_193806_create_restaurant_menus_table.php, storage/api-docs/api-docs.json
=> fix: restaurant menu migration 修正

app/Http/Middleware/UserApproveCheck.php, app/Http/Middleware/UserGoogleApprovedCheck.php
> X
> 사용자 승인 여부를 판단하는 미들웨어의 HTTP 상태코드를 변경
> 
=> Refactor: HTTPステータスコードを変更

app/Http/Controllers/AfterService/AfterServiceController.php, app/Http/Controllers/Salon/SalonReservationController.php
> X
> AS를 최신순으로 불러오도록 수정
> 미용실 예약을 삭제하는 기능의 파라미터를 url로 받도록 수정
> 
=> Refactor: ASおよび、美容室関連機能を修正

app/Http/Controllers/Administrator/NoticeController.php, routes/api.php, storage/api-docs/api-docs.json
> ex) X
> 공지사항 3건만 불러오는 기능 구현
> 
=> Feat: 3件のnoticeを読み込む機能を実装

app/Http/Controllers/Administrator/BusScheduleController.php, app/Http/Controllers/Restaurant/RestaurantMenusController.php, app/Imports/RestaurantMenuImport.php, app/Models/RestaurantMenu.php, app/Models/RestaurantMenuDate.php, database/migrations/2024_03_04_111524_create_bus_schedules_table.php, database/migrations/2024_03_07_203208_create_restaurant_menu_dates_table.php, database/migrations/2024_03_11_193806_create_restaurant_menus_table.php, routes/api.php
> 버스, 식수 API및 식단표 마이그레이션 수정
> 
=> fix: bus, restaurant API, migration 修正

app/Http/Controllers/AfterService/AfterServiceController.php, routes/api.php
> ex) X
> AS 수정 시 라우트 오류 수정
> 과거순으로 불러오도록 수정
> 
=> Fix: AS関連機能を修正

app/Http/Middleware/TokenType.php, routes/api.php
> ex) #318 
> 미들웨어의 파라미터에 맞는 토큰인지 검증하도록 구현하였습니다.
> 
=> Feat: トークンのタイプをチェックするミドルウェアを実装

routes/api.php
> X
> 미용실 영업시간을 불러오는 API를 관리자도 사용할 수 있도록 라우트 수정
> 
=> Refactor: 美容室のrouteを修正

app/Http/Controllers/Administrator/BusScheduleController.php, app/Http/Controllers/Restaurant/RestaurantMenusController.php, app/Http/Controllers/Restaurant/RestaurantSemesterController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php, app/Models/RestaurantSemester.php, app/Models/RestaurantWeekend.php, routes/api.php, storage/api-docs/api-docs.json
> restaurant_menu 1달치, 하루치 불러오기 API 제작
> 
=> feat: restaurant_menu month,day Get 作成

app/Http/Controllers/Salon/SalonBreakTimeController.php
> X
> 미용실 영업시간을 불러오는 기능의 에러 해결
> 
=> Fix: 美容室関連機能のエラーを解決

app/Http/Controllers/Administrator/AbsenceController.php, app/Http/Controllers/Administrator/NoticeController.php, app/Http/Controllers/AfterService/AfterServiceCommentController.php, app/Http/Controllers/AfterService/AfterServiceController.php, app/Http/Controllers/MeetingRoom/MeetingRoomController.php, app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php, app/Http/Controllers/Salon/SalonBreakTimeController.php, app/Http/Controllers/Salon/SalonBusinessHourController.php, app/Http/Controllers/Salon/SalonCategoryController.php, app/Http/Controllers/Salon/SalonReservationController.php, app/Http/Controllers/Salon/SalonServiceController.php, config/auth.php
> X
> 1. 기본 guard를 admin으로 수정하였습니다.
> 2. controller 클래스가 가지는 authorize 메서드를 오버라이드하여 모델을 주입받지 않아도 되도록 수정
> 
=> Refactor: controllerクラスのautorizeメソッドをカスタム

app/Http/Controllers/RefreshController.php
> X
> 토큰 재발급 시 가드 미설정으로 인한 에러 해결
> 
=> Fix: refreshエラーを解決

app/Http/Controllers/RefreshController.php, app/Services/TokenService.php, routes/api.php
> X
> 라우팅 에러와 리프레시 토큰 발급 시 에러를 해결하였습니다.
> 
=> Fix: refreshエラーをおよにrouteエラー解決

routes/api.php
=> Fix: 美容室予約キャンセルエラーを解決

app/Http/Controllers/Administrator/BusScheduleController.php, routes/api.php, storage/api-docs/api-docs.json
=> bus_round and schedule API 作成

app/Services/ReservedTimeService.php
> ex) X
> 예약된 시간을 반환하는 함수에서, 시간을 정렬하여 반환하도록 구현
> 
=> Refactor: 予約された会議室の時間をソーティングするように修正

config/jwt.php
> X
> JWT의 블랙리스트 설정을 사용하도록 변경하였습니다.
> 
=> Chore: jwtの設定を変更

app/Http/Controllers/Administrator/AbsenceController.php, app/Http/Controllers/Administrator/NoticeController.php, app/Http/Controllers/AfterService/AfterServiceCommentController.php, app/Http/Controllers/AfterService/AfterServiceController.php, app/Http/Controllers/Auth/AdminController.php, app/Http/Controllers/Auth/UserController.php, app/Http/Controllers/Controller.php, app/Http/Controllers/MeetingRoom/MeetingRoomController.php, app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php, app/Http/Controllers/RefreshController.php, app/Http/Controllers/Salon/SalonBreakTimeController.php, app/Http/Controllers/Salon/SalonBusinessHourController.php, app/Http/Controllers/Salon/SalonCategoryController.php, app/Http/Controllers/Salon/SalonReservationController.php, app/Http/Controllers/Salon/SalonServiceController.php, routes/api.php, storage/api-docs/api-docs.json
> ex) #337 #338 
> 전체 컨트롤러에 주석 작성 / API 문서 수정하였습니다.
> 불필요한 코드를 삭제하였습니다.
> 응답 메시지를 통일하였습니다.
> 
=> Refactor: コントローラーのコメント作成および修正

app/Http/Controllers/Restaurant/RestaurantMenusController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php, app/Http/Controllers/Restaurant/SemesterMealTypeController.php, app/Imports/RestaurantMenuImport.php, app/Models/RestaurantMenu.php, app/Models/RestaurantMenuDate.php, database/migrations/2024_03_07_203208_create_restaurant_menu_dates_table.php, database/migrations/2024_03_11_193806_create_restaurant_menus_table.php, routes/api.php
=> feat: restaurant_menu week API 追加

app/Http/Controllers/Auth/UserController.php, storage/api-docs/api-docs.json
> X
> 구글 로그인 시 발생하던 validation error를 해결
> API 문서 수정
> 
=> Fix: vaildationエラーを修正

app/Http/Controllers/Salon/SalonCategoryController.php
> X
> 카테고리 생성 시 키 값이 달라 발생하던 에러를 해결
> 
=> Fix: 美容室のカテゴリ生成エラーを解決

app/Http/Controllers/Administrator/BusScheduleController.php
=> fix: bus API error message

app/Http/Controllers/Auth/AdminController.php
=> Fix: 管理者権限変更機能のエラー解決

app/Http/Controllers/Restaurant/RestaurantSemesterController.php, app/Http/Controllers/Restaurant/SemesterMealTypeController.php, app/Http/Controllers/Restaurant/WeekendMealTypeController.php, routes/api.php
=> feat: restaurant meal_type Get API追加

app/Http/Controllers/Salon/SalonServiceController.php, buildspec.yml, storage/api-docs/api-docs.json
> X
> `AWS 배포를 위해 buildspec.yml` 파일을 생성하였습니다.
> 미용실 서비스 생성 에러를 해결하였습니다.
> 
=> Chore: buildspec.ymlを生成

buildspec.yml
=> Chore: buildspec.ymlを修正

buildspec.yml
> ex) #349 
> `buildspec.yml`에 불필요한 코드 삭제
> `imagedefinitions.json` 생성
> 
=> Chore: buildspec.ymlを修正 & imagedefinitions.jsonを生成

app/Http/Controllers/Salon/SalonServiceController.php
=> Fix: 美容室サービス修正エラーを解決

Dockerfile
> #349 
> `Dockerfile` EXPOSE 포트 변경
> 
=> Chore: Dockerfileを修正

app/Http/Controllers/Restaurant/RestaurantSemesterController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php, app/Http/Controllers/Restaurant/WeekendMealTypeController.php, app/Http/Resources/SemesterApplyResource.php, app/Http/Resources/WeekendApplyResource.php, app/Models/RestaurantSemester.php, app/Models/RestaurantWeekend.php, database/migrations/2024_02_21_212458_create_weekend_meal_types_table.php, routes/api.php, storage/api-docs/api-docs.json
> restaurant 식수 신청 리스트 get 제작
> 
=> feat: restaurant apply list Get API 制作

app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php, app/Http/Controllers/Salon/SalonServiceController.php, app/Policies/SalonBreakTimePolicy.php, routes/api.php, storage/api-docs/api-docs.json
> X
> 미용실 서비스 수정 시, URL 파라미터로 id를 받도록 수정
> 미용실 휴게시간 삭제 기능 에러 해결
> 유저의 회의실 예약을 불러올 때, 정렬하도록 수정
> API 문서 수정
> 
=> Refactor:美容室と会議室関連機能の修正

app/Http/Controllers/Administrator/BusScheduleController.php
=> fix: bus API error message 修正

app/Http/Controllers/Salon/SalonBusinessHourController.php, app/Http/Controllers/Salon/SalonCategoryController.php, storage/api-docs/api-docs.json
> X
> 미용실 카테고리 관련 기능에서 기존 `category_name` 키 값에서 `category`로 변경
> 미용실 영업시간 불러올 시 아이디도 포함하도록 수정
> API 문서 수정
> 
=> Refactor: 美容室関連機能の修正

resources/views/welcome.blade.php
> #349 
> codepipeline 동작 테스트
> 
=> Test: codepipelineテスト

app/Http/Controllers/Restaurant/RestaurantSemesterController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php
=> fix:restaurant user_id 修正

app/Http/Controllers/Salon/SalonBusinessHourController.php, app/Models/MeetingRoomReservation.php, database/migrations/2024_02_17_164259_create_salon_business_hours_table.php, database/seeders/SalonBusinessHourSeeder.php, routes/api.php
> X
> 미용실 영업시간 삭제 기능을 빼고, open 컬럼을 생성하여 영업시간 전체를 닫을 수 있게 스키마 수정
> 스키마 수정에 맞추어 기능 수정
> 회의실 예약 정보를 불러올 때 시간:분 으로 불러오도록 포맷 수정
> 
=> Migrate: 美容室の営業時間テーブルを修正

codepipeline.md
=> Test: codepipelineのテスト

appspec.yaml
> #363 
> 배포시 사용할 `appspec.yaml` 작성
> 
=> Chore: appspec.yamlを作成

app/Http/Controllers/AfterService/AfterServiceController.php
> X
> AS 관련 로직에서 유저의 휴대폰 번호도 불러오도록 수정
> 
=> Refactor: 連関関係を修正

app/Http/Controllers/AfterService/AfterServiceCommentController.php
> X
> AS 댓글 삭제 에러를 해결하였습니다.
> 
=> Fix: ASのコメント削除エラーを解決

buildspec.yml
> #363 
> 블루/그린 배포를 사용하기 위해 `imagedefinitions.json`에서 `imageDetail.json`으로 변경
> `buildspec.yml` 내부 코드를 변경된 `imageDetail.json`에 맞게 변경
> 
=> Chore: build関連修正

database/migrations/2024_03_07_203208_create_restaurant_menu_dates_table.php, routes/api.php
=> fix:auth user_id 修正

app/Http/Controllers/Restaurant/RestaurantSemesterController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php, routes/api.php
=> fix:auth user_id 2修正

appspec.yml, taskdef.json
> #363 
> 배포를 위해 `taskdef.json` 생성
> 
=> Chore: taskdef.jsonを生成

app/Services/ReservedTimeService.php
> X
> 회의실의 예약된 시간을 불러올 때, 거절된 예약은 불러오지 않도록 수정
> 
=> Refactor: 会議室の予約時間関連機能の修正

taskdef.json
> #363 
> `taskdef.json` family 구문 추가
> 
=> Chore: taskdef.jsonを修正

appspec.yml
=> Chore: appspec.ymlを修正

app/Http/Controllers/Administrator/BusScheduleController.php, app/Http/Controllers/Restaurant/RestaurantMenusController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php, app/Http/Controllers/Restaurant/SemesterMealTypeController.php, app/Http/Controllers/Restaurant/WeekendMealTypeController.php, app/Models/RestaurantApplySetting.php, database/migrations/2024_03_19_112600_create_restaurant_apply_settings_table.php, routes/api.php, storage/api-docs/api-docs.json
> fix:restaurant API swagger 수정
> 
=> fix:restaurant API swagger修正

app/Http/Controllers/Restaurant/RestaurantSemesterController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php
=> fix: restaurant user_id ex

Dockerfile.nginx, nginx/default.conf
> #363 
> nginx 관련 도커 파일 및 설정 파일 수정
> 
=> Chore: nginx関連ファイルを修正

app/Http/Controllers/Auth/AdminController.php, app/Http/Controllers/Auth/UserController.php, database/migrations/2024_01_29_070101_create_salon_reservations_table.php, routes/api.php, storage/api-docs/api-docs.json
> X
> 관리자 및 유저의 정보를 반환하는 기능 구현
> 마이그레이션 파일 수정(soft delete 삭제)
> API 문서 수정
> 
=> Feat: 管理者およびユーザーの情報を読み込む機能を実装

app/Http/Controllers/Controller.php, app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php
> X
> 미용실 영업시간 관련 에러를 수정
> 주석 추가
> 
=> Fix: 美容室の営業直関連エラーを解決

app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php, app/Http/Controllers/Restaurant/RestaurantSemesterController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php, app/Models/RestaurantSemester.php, storage/api-docs/api-docs.json
> restaurant_Apply_division API swagger 수정
> 
=> fix:restaurant_Apply_division API swagger修正

app/Http/Controllers/Administrator/BusScheduleController.php, app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php, app/Http/Controllers/Restaurant/RestaurantSemesterController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php, app/Http/Controllers/Restaurant/SemesterMealTypeController.php, app/Http/Controllers/Restaurant/WeekendMealTypeController.php, routes/api.php, storage/api-docs/api-docs.json
> restaurant_meal_type get API 수정
> 
=> fix:restaurant_meal_type get API 修正

app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php, routes/api.php, storage/api-docs/api-docs.json
> feat:restaurant_apply get API 작성
> 
=> feat:restaurant_apply get API 作成

app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php, routes/api.php, storage/api-docs/api-docs.json
> restaurant_apply App get API 작성
> 
=> feat:restaurant_apply App get API 作成

app/Models/SalonReservation.php
> X
> softdelete trait로 인해 쿼리 시 에러 발생 해결
> 
=> Fix: 美容室検索エラーを解決

app/Policies/NoticePolicy.php
=> Fix: noticeの削除エラーを解決

app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php, app/Http/Controllers/Restaurant/RestaurantSemesterController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php, routes/api.php
> 식수 리스트 검색기능, 리스트 보기 기능 합침
> 
=> fix:restaurant_show API 修正

app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php, app/Http/Controllers/Restaurant/RestaurantSemesterController.php, routes/api.php
> restaurant_user_show API 수정
> 
=> fix:restaurant_user_show API 修正

app/Http/Controllers/Auth/UserController.php, composer.json, composer.lock
> #322 
> 한국어
1. `google/apiclient` 패키지 설치
2. 구글 로그인 시 클라이언트로 부터 반환된 `id_token`을 검증하도록 구현
> 일본어
1. `google/apiclient` パッケージのインストール
2. Google ログインの時、クライアントから返された `id_token` を検証するように実装
>
=> Refactor: googleログイン機能を修正

database/migrations/2024_03_07_203208_create_restaurant_menu_dates_table.php
> X
> 한국어
1. restaurant_menu_dates 수정
> 일본어
1. restaurant_menu_dates 修正
>
=> fix:restaurant_menu_dates 修正

app/Http/Controllers/Restaurant/RestaurantAccountController.php, app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php, app/Models/RestaurantAccount.php, app/Models/RestaurantApplyState.php, database/migrations/2024_03_21_132216_create_restaurant_apply_states_table.php, database/migrations/2024_03_25_193642_create_restaurant_accounts_table.php, routes/api.php, storage/api-docs/api-docs.json
> 
> 한국어
1. 식수 계좌 테이블, API만듬
> 일본어
1. restaurant account table,API 作成
>
=> feat:restaurant account table,API 作成

routes/api.php
> X
> 한국어
1. approve 체크하는 미들웨어 제외하였습니다.
> 일본어
1. approveをチェックするミドルウェアを除外しました。
>
=> Fix: approveをチェックするmiddlewareを削除

app/Http/Controllers/Restaurant/RestaurantAccountController.php, app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php, app/Http/Controllers/Restaurant/SemesterMealTypeController.php, app/Http/Controllers/Restaurant/WeekendMealTypeController.php, app/Models/RestaurantAccount.php, database/migrations/2024_03_25_193642_create_restaurant_accounts_table.php, routes/api.php, storage/api-docs/api-docs.json
> 
> 한국어
1. restaurant account,meal_type API 수정
> 일본어
1. restaurant account,meal_type API 修正
>
=> fix:restaurant account,meal_type API 修正

app/Http/Controllers/Administrator/BusScheduleController.php, app/Http/Controllers/Restaurant/RestaurantMenusController.php, app/Imports/RestaurantMenuImport.php, database/seeders/BusRouteSeeder.php, database/seeders/RestaurantMenuDateSeeder.php, routes/api.php, storage/api-docs/api-docs.json
> 
> 한국어
1. 버스 스케줄 수정 API
> 일본어
1. bus_schedules API 修正
>
=> fix:bus_schedules API 修正

app/Http/Controllers/Administrator/BusScheduleController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php, routes/api.php, storage/api-docs/api-docs.json
> 
> 한국어
1. restaurant apply user API 수정
> 일본어
1. restaurant apply user API 修正
>
=> fix:restaurant apply user API 修正

app/Http/Controllers/Administrator/NoticeController.php, routes/api.php
> #419 
> 한국어
1. `bus`, `admin` 태그를 가진 긴급 공지 중, 가장 최근 하나만 불러오는 기능을 구현하였습니다.
> 일본어
1. `bus`、`admin` タグを持つ緊急通知の中で、最新の1つだけを読み込む機能を実装しました。
>
=> Feat: 最新の緊急お知らせを読み込む機能を実装

app/Services/ResetPasswordService.php
> #417 #415 
> 한국어
1. 공통적으로 사용되는 코드 생성 부분을 Service 클래스로 분리하였습니다.
> 일본어
1. 共通に使用されるコード生成部分をServiceクラスに分離しました。
>
=> Feat: パスワードをリセットするサービスを実装

app/Http/Middleware/Authenticate.php, config/auth.php, routes/api.php
> X
> 한국어
1. API에러 해결
> 일본어
1. APIエラーを解決
>
=> HOTFIX: APIエラーを解決

app/Http/Controllers/Auth/AdminController.php
> X
> 한국어
1. 관리자의 목록을 받아오는 기능에서, 유저를 반환하지 않도록 에러를 해결하였습니다.
> 일본어
1. 管理者のリストを取得する機能で、ユーザーを返さないようにエラーを解決しました。
>
=> Fix: 管理者関連機能のエラーを解決

app/Http/Controllers/Restaurant/RestaurantAccountController.php, app/Http/Controllers/Restaurant/RestaurantSemesterController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php, storage/api-docs/api-docs.json
> 
> 한국어
1. :restaurant_weekend sumApplyWeb 작성
> 일본어
1. restaurant_weekend sumApplyWeb 作成
>
=> feat:restaurant_weekend sumApplyWeb 作成

routes/api.php
> X
> 한국어
1. 회의실 수정 에러 해결
> 일본어
1. 会議室の修正機能のエラーを解決
>
=> Fix: 会議室の修正機能のエラーを解決

app/Http/Controllers/Auth/AdminController.php, app/Http/Controllers/Auth/UserController.php, app/Http/Controllers/Controller.php, routes/api.php
> #425 
> 한국어
1. 테이블 통합으로 인한 유효성 검사 룰 수정
2. 테이블 통합으로 인한 이메일 검사 중복 기능 제거
3. 구글 로그인 에러 해결
> 일본어
1. テーブルの統合に伴うバリデーションルールの修正を行いました。
2. テーブルの統合に伴い、メールアドレスの重複チェック機能を削除しました。
3. googleログインエラーを解決
>
=> Refactor: adminのメール確認機能を削除

app/Http/Controllers/Administrator/AbsenceController.php, storage/api-docs/api-docs.json
> X 
> 한국어
1. 외박 신청 시 중복되는 값이 있을 경우 발생하는 에러의 HTTP 상태 코드 변경하였습니다.
> 일본어
1. 外泊を申し込むときに重複する値がある場合に発生するエラーのHTTPステータスコードを変更しました。
>
=> Refactor: 外泊申請機能のHTTPステータスコードを変更

app/Policies/AbsenceListPolicy.php, app/Policies/AfterServiceCommentPolicy.php, app/Policies/AfterServicePolicy.php, app/Policies/MeetingRoomPolicy.php, app/Policies/MeetingRoomReservationPolicy.php, app/Policies/NoticePolicy.php, app/Policies/SalonBreakTimePolicy.php, app/Policies/SalonBusinessHourPolicy.php, app/Policies/SalonCategoryPolicy.php, app/Policies/SalonReservationPolicy.php, app/Policies/SalonServicePolicy.php, routes/api.php
> #425 
> 한국어
1. 수정된 유저 테이블에 맞추어 관리자만 이용가능한 API에 정책을 수정하였습니다.
> 일본어
1. 修正したユーザーテーブルに合わせて、管理者専用のAPIにポリシーを修正しました。
>
=> Refactor: 新しいユーザーテーブルに合わせてpolicyを修正

app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php, app/Imports/RestaurantMenuImport.php, routes/api.php, storage/api-docs/api-docs.json
> 
> 한국어
1. restaurant_apply_division API 수정
> 일본어
1. restaurant_apply_division API 修正
>
=> fix:restaurant_apply_division API 修正

app/Http/Controllers/Administrator/NoticeController.php, app/Http/Controllers/AfterService/AfterServiceCommentController.php, app/Http/Controllers/AfterService/AfterServiceController.php, app/Http/Controllers/Auth/AdminController.php, app/Http/Controllers/Auth/UserController.php, app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php, app/Http/Controllers/Salon/SalonBusinessHourController.php, app/Http/Controllers/Salon/SalonReservationController.php, app/Http/Controllers/Salon/SalonServiceController.php, storage/api-docs/api-docs.json
> X
> 한국어
1. 필요없는 주석 삭제했습니다.
2. if문을 최소화했습니다.
3. API 문서를 수정했습니다.
> 일본어
1. 不要なコメントを削除しました。
2. if文を最小限にしました。
3. APIドキュメントを修正しました。
>
=> Refactor: 全体コード改善

app/Http/Controllers/Auth/AdminController.php, app/Http/Controllers/Salon/SalonBreakTimeController.php, app/Http/Controllers/Salon/SalonBusinessHourController.php, app/Http/Controllers/Salon/SalonCategoryController.php, app/Http/Controllers/Salon/SalonReservationController.php, app/Http/Controllers/Salon/SalonServiceController.php
> X
> 한국어
1. 유효성 검사 규칙 오타를 수정하였습니다.
2. 정책으로 인해 API 접근이 안되는 오류를 해결하였습니다.
> 일본어
1. バリデーションルールのタイプミスを修正しました。
2. ポリシーによりAPIへのアクセスができないエラーを解決しました。
>
=> Fix: エラーを解決

app/Console/Kernel.php, routes/api.php
> #445 
> 한국어
1. 비밀번호 코드를 정리하는 작업에 대해서, 6시간마다 하나의 서버에서 실행되도록 수정하였습니다.
> 일본어
1. パスワードリセットコードを整理する作業について、6時間ごとに1つのサーバーで実行されるように修正しました。
>
=> Refactor: scheduled jobを修正

app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php, app/Http/Controllers/Restaurant/RestaurantMenusController.php, app/Imports/RestaurantMenuImport.php, storage/api-docs/api-docs.json
> 
> 한국어
1. restaurant_menu, apply API 수정
> 일본어
1. restaurant_menu, apply API 修正
>
=> fix:restaurant_menu, apply API 修正

routes/api.php
> X
> 한국어
1. 유저 정보 수정 에러 해결하였습니다.
> 일본어
1. ユーザー情報修正エラーを解決しました。
>
=> Fix: ユーザー情報修正エラーを解決

app/Http/Controllers/Administrator/NoticeController.php
> X
> 한국어
1. notice 연관관계 에러 해결
> 일본어
1. notice連関関係エラーを解決
>
=> Fix: noticeの連関関係エラーを解決

app/Http/Controllers/Administrator/NoticeController.php
> X
> 한국어
1. 공지사항 연관관계 에러 해결하였습니다.
> 일본어
1. notice連関関係エラーを解決しました。
>
=> Fix: noticeの検索エラーを解決

app/Http/Controllers/Auth/AdminController.php, app/Http/Controllers/Auth/UserController.php
> X
> 한국어
1. 회원정보 수정 시 유효성 검사 규칙으로 인해 발생하던 에러를 해결하였습니다.
2. 관리자의 회원가입 시, approved 컬럼이 true로 설정되어 있던 것을 수정하였습니다.
> 일본어
1. ユーザー情報の修正時に発生していたバリデーションルールによるエラーを解決しました。
2. 管理者のユーザー登録時に、approvedカラムがtrueに設定されていた問題を修正しました。
>
=> Fix: ユーザーと管理者のエラーを解決

app/Http/Controllers/Auth/AdminController.php
> X
> 한국어
1. adminList에서 관리자 목록을 반환할 때 객체가 아니라 배열로 반환하도록 수정하였습니다.
> 일본어
1. adminListから管理者のリストを返す際に、オブジェクトではなく配列として返すように修正しました。
>
=> Fix: adminList関数のresponseを修正

app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php, routes/api.php
> 
> 한국어
1. restaurant_apply_division Web API 추가
> 일본어
1. restaurant_apply_division Web API 追加
>
=> feat:restaurant_apply_division Web API 追加

app/Http/Controllers/Auth/UserController.php, routes/api.php
> #407 
> 한국어
1. `UserController`의 `update` 메서드를 `approve` 미들웨어에서 제외하고, 로직 내에서 승인 여부를 체크하여 다르게 동작하도록 개선하였습니다.
> 일본어
1. `UserController`の`update`メソッドを`approve`ミドルウェアから除外し、ロジック内で承認状況をチェックして異なる動作をするように改善しました。
>
=> Refactor: ユーザー情報修正機能を改善

app/Http/Controllers/Auth/AdminController.php, app/Http/Controllers/Auth/PasswordResetCodeController.php, app/Http/Controllers/Auth/UserController.php, routes/api.php, storage/api-docs/api-docs.json
> X
> 한국어
1. 비밀번호 관련 중복되는 함수를 삭제하고, 경로를 변경하였습니다.
2. 이메일 찾기 경로를 변경하였습니다.
> 일본어
1. パスワード関連の重複する関数を削除し、routeを変更しました。
2. メールアドレスの検索routeを変更しました。
>
=> Refactor: routeを変更

routes/api.php
> X
> 한국어
1. 미용실 카테고리 라우트 에러 해결하였습니다.
> 일본어
1. 美容室のカテゴリールートのエラーを解決しました。
>
=> Fix: routeエラーを解決

app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php, database/migrations/2024_02_21_212448_create_semester_meal_types_table.php, database/migrations/2024_02_21_212458_create_weekend_meal_types_table.php, database/migrations/2024_03_04_111500_create_bus_rounds_table.php, database/migrations/2024_03_04_111524_create_bus_schedules_table.php, database/migrations/2024_03_07_203208_create_restaurant_menu_dates_table.php, database/migrations/2024_03_11_193806_create_restaurant_menus_table.php, database/migrations/2024_03_25_193642_create_restaurant_accounts_table.php, routes/api.php
> 
> 한국어
1. restaurant migration 수정
> 일본어
1. restaurant migration 修正
>
=> fix:restaurant migration 修正

app/Http/Kernel.php, config/session.php
> X
> 한국어
1. Sanctum 관련 미들웨어를 주석처리하였습니다.
2. https 관련 설정을 수정하였습니다.
> 일본어
1. Sanctum関連のミドルウェアをコメントアウトしました。
2. HTTPS 関連の設定を修正しました。
>
=> Chore: 認証関連設定を修正

.github/workflows/create_release.yml
> X
> 한국어
1. 릴리스 시 PR을 참조하여 태그를 생성하도록 하였습니다.
> 일본어
1. リリースする時、PRを参照してタグを生成するようにしました。
>
=> Refactor: release用のactionを修正

.github/workflows/create_release.yml, .github/workflows/deployment.yml
> X
> 한국어
1. 테스트를 위해 릴리즈 액션의 버전을 하드코딩하였습니다.
2. 배포 워크플로우를 트리거하는 플로우의 이름을 수정하였습니다.
> 일본어
1. テストのため、リリースactionのバージョンをハードコーディングしました。
2.デプロイワークフローをトリガーするフローの名を修正しました。
>
=> Fix: deployment用のactionを修正

.github/workflows/add_pull_request_assignee.yml, .github/workflows/create_release.yml, .github/workflows/deployment.yml
> X
> 한국어
1. job 이름을 수정하였습니다.
2. deplotment.yml 파일 형식 에러를 수정하였습니다.
> 일본어
1. job名を修正しました。
2. deplotment.ymlファイル形式エラーを修正しました。
>
=> Fix: デプロイエラーを解決

.github/workflows/create_release.yml
> X
> 한국어
1. GITHUB_TOKEN을 이용하여 인증하도록 수정
> 일본어
1. GITHUB_TOKENを利用して認証するように修正
>
=> Refactor: GITHUB_TOKENを利用

app/Http/Controllers/Auth/AdminController.php, app/Http/Controllers/Auth/UserController.php, app/Http/Controllers/Controller.php, app/Http/Requests/LoginRequest.php
> #447 
> 한국어
로그인 로직에 FormRequest를 사용하여 try-catch문을 최소화하고 유효성검사 규칙을 통일하였습니다.
> 일본어
ログイン機能にFormRequestを利用し、try-catchの最小化およびvalidationルールを一貫しました。
Refactor인데 커밋메시지 잘못 적음..
=> Refactor: ログインにformRequestを適用

config/jwt.php, resources/views/mail/password.blade.php
> X
> 한국어
1. 이메일 본문 오타 수정
2. 토큰 시간을 5분으로 수정
> 일본어
1. メール本文の誤りを修正しました。
2. トークンの時間を5分に変更しました。
>
=> Refactor: メール形式を修正、トークンの時間修正

app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php, app/Http/Controllers/Restaurant/RestaurantMenusController.php, app/Http/Controllers/Restaurant/SemesterMealTypeController.php, app/Http/Controllers/Restaurant/WeekendMealTypeController.php, routes/api.php
> 
> 한국어
1. fix:restaurant_meal_type and apply API 수정
> 일본어
1. fix:restaurant_meal_type and apply API 修正
>
=> fix:restaurant_meal_type and apply API 修正

app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php, app/Http/Controllers/Restaurant/RestaurantSemesterController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php, storage/api-docs/api-docs.json
> 
> 한국어
1. 필요없는 restaurant_apply_division API 삭제 그리고 swagger 수정
> 일본어
1. restaurant_apply_division API and swagger 修正
>
=> remove:restaurant_apply_division API and swagger 修正

app/Http/Middleware/Authenticate.php
> X
> 한국어
1. header의 `access token` 확인 후, `refresh token`을 확인하도록 수정
> 일본어
1. headerの `access token`を確認してから、`refresh token`を確認するように修正
>
=> Fix: 認証middlewareを修正

app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php, app/Http/Middleware/Authenticate.php
> X
> 한국어
1. 배포 테스트
> 일본어
1. デプロイテスト
>
=> Test: デプロイテスト

app/Http/Controllers/Auth/UserController.php
> X
> 한국어
1. 비밀번호 검증 기능을 유효성 검사 규칙을 통해 검증하도록 개선하였습니다.
> 일본어
1. パスワード検証機能をvalidationルールを利用して検証するように改善しました。
>
=> Refactor: パスワードの検証機能を改善

app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
> 
> 한국어
1. restaurant_apply_division API weekendCheck,semesterCheck수정
> 일본어
1. restaurant_apply_division API weekendCheck,semesterCheck修正
>
=> fix:restaurant_apply_division API weekendCheck,semesterCheck修正

app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
> 
> 한국어
1. restaurant_apply_division weekendCheck API 수정
> 일본어
1. restaurant_apply_division weekendCheck API 修正
>
=> fix:restaurant_apply_division weekendCheck API 修正

app/Http/Controllers/Restaurant/RestaurantSemesterController.php, app/Http/Controllers/Restaurant/RestaurantWeekendController.php, app/Models/RestaurantWeekend.php, routes/api.php, storage/api-docs/api-docs.json
> 
> 한국어
1. restaurant payment API 수정
> 일본어
1. restaurant payment API 修正
>
=> fix:restaurant payment API 修正

app/Http/Controllers/Auth/AdminController.php
> X
> 한국어
1. 관리자 개인정보 수정 시, 유효성 검사 규칙으로 인해 발생하는 에러 해결
> 일본어
1. 管理者の個人情報の修正時、validation ルールによって発生するエラーを解決
>
=> Fix: 管理者の情報修正エラーを解決

app/Http/Middleware/AuthenticateRefresh.php
> X
> 한국어
1. 리프레시 토큰 검증 시, 헤더의 토큰도 검증하도록 수정
> 일본어
1. リフレッシュトークンを検証する時、Headerのトークンも検証するように修正
>
=> Fix: アプリのリフレッシュエラーを解決

app/Http/Controllers/Administrator/AbsenceController.php, app/Http/Controllers/Administrator/NoticeController.php, app/Http/Controllers/AfterService/AfterServiceCommentController.php, app/Http/Controllers/AfterService/AfterServiceController.php, app/Http/Controllers/Auth/AdminController.php, app/Http/Controllers/Auth/PasswordResetCodeController.php, app/Http/Controllers/Auth/PrivilegeController.php, app/Http/Controllers/Auth/RefreshController.php, app/Http/Controllers/Auth/UserController.php, app/Http/Controllers/MeetingRoom/MeetingRoomController.php, app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php, app/Http/Controllers/Restaurant/RestaurantMenusController.php, app/Http/Controllers/Salon/SalonBreakTimeController.php, app/Http/Controllers/Salon/SalonBusinessHourController.php, app/Http/Controllers/Salon/SalonCategoryController.php, app/Http/Controllers/Salon/SalonReservationController.php, app/Http/Controllers/Salon/SalonServiceController.php
> X
> 한국어
1. 컨트롤러의 모든 함수에 리턴 타입을 명시하고, 중복되는 타입은 import하여　간략하게 수정하였습니다.
> 일본어
1. コントローラの全ての関数にリターンタイプを明示し、重複されるタイプはimportして手短に修正しました。
>
=> Refactor: リターンタイプの整理

Dockerfile, app/Http/Controllers/AfterService/AfterServiceController.php
> X
> 한국어
1. `Dockerfile` 수정
2. as 유효성 검사 규칙 수정
> 일본어
1. `Dockerfileを修正
2. asのvalidationルールを修正
>
=> Fix: イメージエラー解決

config/jwt.php
> X
> 한국어
1. 토큰 시간 5 -> 300 변경
> 일본어
1. トークンの有効時間を5分→300分に変更
>
=> Refactor: トークンの有効時間変更

app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
> 
> 한국어
1. restaurant_apply_division API수정
> 일본어
1. restaurant_apply_division API修正
>
=> fix:restaurant_apply_division API修正

app/Http/Controllers/Restaurant/RestaurantMenusController.php, app/Http/Kernel.php, app/Http/Middleware/Cors.php
> 
> 한국어
1. restaurant_menu upload middleware Cors구현
> 일본어
1. restaurant_menu upload middleware Cors具現
>
=> feat:restaurant_menu upload middleware Cors具現

composer.json, composer.lock
> X
> 한국어
1. 전체적인 패키지 업데이트
2. `composer.json`에 laravel 버전 추가
> 일본어
1. 全体的なパッケージのアップデート
2. `composer.json`にlaravelのバージョンを追加
>
=> Chore: パッケージのアップデート

app/Models/User.php, composer.json, composer.lock, config/firebase.php, database/migrations/2014_10_12_000000_create_users_table.php
> #519 #520 
> 한국어
1. `laravel-firebase` 설치
2. users 테이블 수정
> 일본어
1. `laravel-firebase` をインストール
2. users テーブルを修正
>
=> Chore: laravel-firebaseを追加

config/app.php, database/migrations/2024_03_04_111500_create_bus_rounds_table.php
> X
> 한국어
1. `bus_rounds` 테이블 수정
2. broadcast 프로바이더 주석처리
> 일본어
1. `bus_rounds`テーブル修正
2. broadcastプロバイダコメント処理
>
=> Migration: バステーブルを修正

app/Http/Controllers/Auth/UserController.php
> X
> 한국어
1. 로그인 에러 해결했습니다.
> 일본어
1. ログインエラーを解決しました。
>
=> Fix: ログインエラーを解決

app/Http/Controllers/Administrator/AbsenceController.php, app/Http/Controllers/Administrator/NoticeController.php, app/Http/Controllers/AfterService/AfterServiceCommentController.php, app/Http/Controllers/AfterService/AfterServiceController.php, app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php, app/Http/Controllers/Salon/SalonReservationController.php, app/Services/NotificationService.php
> X
> 한국어
1. 서비스에서 보여줄 페이지의 기본 값을 설정하여 필수 파라미터로 적지 않아도 되도록 수정하였습니다.
2. 단체 알람 발송에서 토큰이 없거나 조건에 부합하는 유저가 없는 경우 알림 발송 로직이 동작하지 않도록 수정하였습니다.
> 일본어
1. サービスで表示するページのデフォルト値を設定して、必須パラメーターを書かなくてもように修正しました。
2. グループ通知の送信でトークンがないか、条件に合うユーザーがいない場合は通知送信ロジックが動作しないように修正しました。
>
=> Refactor: プッシュ通知機能を改善

app/Http/Kernel.php, app/Http/Middleware/Authenticate.php, app/Http/Middleware/AuthenticateEmail.php, routes/api.php
> X
> 한국어
1. 이메일 토큰을 인증하는 미들웨어를 구현했습니다.
2. 이메일 초기화 시 발생하는 에러를 해결하였습니다.
> 일본어
1. メールトークンの認証を行うミドルウェアを実装しました。
2. メールの初期化時に発生するエラーを解決しました。
>
=> Feat: email認証middlewareを実装

app/Http/Controllers/Auth/UserController.php, routes/api.php, storage/api-docs/api-docs.json
> 
> 한국어
1. 푸시 알림 수신여부를 설정하는 API를 구현했습니다.
2. API 문서를 수정했습니다.
> 일본어
1. プッシュ通知の可否を設定する機能を実装しました。
2. API文書を修正しました。
>
=> Feat: プッシュ通知の可否を設定する機能を実装

app/Http/Controllers/Salon/SalonReservationController.php
> X
> 한국어
1. 미용실 푸시알림 발신 에러를 해결했습니다.
> 일본어
1. 美容室のプッシュ通知エラーを解決しました。
>
=> Fix: 美容室のプッシュ通知エラーを解決

Dockerfile, app/Console/Kernel.php, app/Services/NotificationService.php, app/Tasks/RestaurantSemesterNotification.php, app/Tasks/RestaurantWeekendNotification.php, crontab, routes/api.php
> #532 
> 한국어
1. 불필요한 라우트 제거
2. 주말, 학기 식수신청 푸시알림 구현
3. 푸시알림 서비스 클래스 개선
4. cron 실행을 위한 crontab 파일 생성
5. cron 실행하도록 도커파일 수정
> 일본어
1. 
>
=> Feat: 週末、学期食事申請のプッシュ通知を実装

.github/workflows/cron_integration.yml
> X
> 한국어
1. 도커 리포지토리 명 수정
> 일본어
1. Dockerのリポジトリ名を修正
>
=> Chore: ワークフローを修正

Dockerfile-cron
> X
> 한국어
1. 스케줄용 도커파일 수정
> 일본어
1. schedule用のDockerfileを修正
>
=> Chore: schedule用のDockerfileを修正

config/firebase.php
> X
> 한국어
1. json을 참조하던 firebase의 설정을 환경변수로 변경하였습니다.
> 일본어
1. jsonを参照していたfirebaseの設定を環境変数に変更しました。
>
=> Chore: firebaseの設定を変更

app/Http/Controllers/Restaurant/RestaurantMenusController.php
> 
> 한국어
1. fix:restaurant_menu api getWeekMenu 수정
> 일본어
1. fix:restaurant_menu api getWeekMenu 修正
>
=> fix:restaurant_menu api getWeekMenu 修正

app/Http/Controllers/QRController.php, app/Http/Controllers/Restaurant/RestaurantMenusController.php
> 
> 한국어
1. getWeekMenu API 배열로 수정
> 일본어
1. getWeekMenu API 修正
>
=> fix:getWeekMenu API 修正

app/Http/Controllers/QRController.php, app/Http/Controllers/Restaurant/RestaurantMenusController.php, routes/api.php, storage/api-docs/api-docs.json
> 
> 한국어
1. feat:QRController API 작성
> 일본어
1. feat:QRController API作成
>
=> feat:QRController API作成

Dockerfile.nginx, appspec.yml, nginx/default.conf
> X
> 한국어
1. nginx 포트를 80->443으로 변경하였습니다.
> 일본어
1. nginxのポートを80から443に変更しました。
>
=> Chore: ポートを変更

app/Http/Controllers/QRController.php
> 
> 한국어
1. fix:QRController check API 수정
> 일본어
1. fix:QRController check API 修正
>
=> fix:QRController check API 修正

app/Http/Controllers/QRController.php
> X
> 한국어
1. QR에러 해결
> 일본어
1. QRエラーを解決
>
=> Fix: QRエラーを解決

composer.json, composer.lock, config/broadcasting.php, config/cors.php, config/wave.php
> #572 
> 한국어
1. laravel-wave 설치
> 일본어
1. laravel-waveインストール
>
=> Add: SSE実装のためにlaravel-waveをインストール

.github/workflows/auto_assign.yml, app/Events/ServerSideEvent.php, app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php, app/Http/Controllers/Salon/SalonReservationController.php, config/database.php, routes/api.php
> #572 
> 한국어
1. 미용실 및 회의실 예약 시 SSE를 트리거하도록 구현
> 일본어
1. 美容室および会議室の予約を行う時、SSEをトリガーするように実装
>
=> Feat: SSE機能を追加

routes/api.php
> #572 
> 한국어
1. SSE 테스트 라우트 추가
> 일본어
1. SSEテストルーツを追加
>
=> Feat: SSEテストルーツを追加

Dockerfile
> #572 
> 한국어
1. Dockerfile 수정
> 일본어
1. Dockerfile修正
>
=> Chore: Dockerfile修正

config/database.php
> #572 
> 한국어
1. database.php 수정
> 일본어
1. database.phpを修正
>
=> Chore: database.phpを修正

config/wave.php
> #572 
> 한국어
1. wave 라우트 변경
> 일본어
1. waveルーツを変更
>
=> Chore: waveルーツを変更
